# instance configuration for authorization template
# compose the inputs for adapter using istio attributes
apiVersion: "config.istio.io/v1alpha2"
kind: authorization
metadata:
  name: authzrequestcontext
  namespace: istio-system
spec:
  subject:
    user: request.auth.principal | ""
    groups: request.auth.principal | ""
    properties:
      service: source.service | ""
      namespace: source.namespace | ""
  action:
    namespace: destination.namespace | ""
    service: destination.service | ""
    method: request.method | ""
    path: request.path | ""
    properties:
      token: request.headers["authorization"] | ""
---
# handler configuration for authz adapter
apiVersion: "config.istio.io/v1alpha2"
kind: authz
metadata:
 name: handler
 namespace: istio-system
spec:
 service_url: "http://hp-authz-service.hp/authz/v1/authorize"
 cache_duration: "1s"
---
# rule to dispatch to the handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: authzrule
  namespace: istio-system
spec:
  match: destination.labels["layer"] == "L1"
  #match: "true"
  #match: destination.service == "hp-backoffice-service.hp.svc.cluster.local"
  #match: request.headers["x-user"] == "user1"
  #match: destination.name	== "hp-backoffice-service"
  actions:
  # handler and instance names default to the rule's namespace.
  - handler: handler.authz
    instances:
    - authzrequestcontext.authorization
---